theme: jekyll-theme-cayman
title: Data-Driven Machinery Fault Diagnosis
description: Personal Project of <a href="https://biswajitsahoo1111.github.io/" style= "color:purple" target="_blank">Biswajit Sahoo</a>
show_downloads: "true"
google_analytics: UA-153389754-1
